guides/prefetching.md
This is currently documented but burried https://docs.layer0.co/docs/api/prefetch/modules/_window_install_.html#defaults.includecachemisses
=> Add includeCacheMisses to prefetching guide

guides/traditional_sites.md
manual adding of scripts has been superseded by injection via transformation
=> Remove Add Scripts to your site

routes.js
=> Include *.segment.com in the CSP

components/nav/Nav.js
Make sure that links like https://docs.layer0.co/guides/react#section_deploying open the containing menu item
=> Open menu with anchor links

components/nav/Nav.js, pages/index.js
- Fix version links in nav
- Fixes home page styles in Safari
=> Styles and Version

guides/nuxt.md
=> Update nuxt guide with the latest steps

guides/production.md
=> Update production.md to fix typos

guides/image_optimization.md
=> Corrected Image Optimizations

guides/core_web_vitals.md
fixed typos and heading consistency
=> Corrections to Core Web Vitals

guides/overview.md
=> Corrected Overview

guides/deploy_apps.md
minor corrections for grammar and consistency
=> Corrections to Deploying

guides/graphql.md
This one slipped through the cracks on the first round of edits.
=> Corrected typo on GraphQL

guides/webapp_cdn_getting_started.md
minor corrections for grammar and consistency
=> Corrected WebApp CDN

guides/routing.md
corrected heading capitalization and reference inconsistencies
=> Corrected Routing.md

guides/purging.md
matched text to referenced image
=> Corrected Purging

guides/third_party_cdns.md
=> Corrections to 3rdParty CDNs

guides/cookbook.md
heading capitalization inconsistency
whitelisting > allow IPs
=> Corrections to Cookbook.md

guides/production.md
corrected:
heading inconsistencies
i.e. > e.g.
whitelisting > allow IPs
inconsistent references to notes
=> Corrections to Custom Domain/SSL

components/Markdown.js
We need to capture this data for analytics
=> Removing noreferrer from external links

guides/security.md, package-lock.json, package.json
=> resized security images

guides/prefetching.md
@tristanlee85 , please review.
=> add description of cache-manifest.js

pages/index.js, routes.js
This is for https://app.clickup.com/t/2b96xn7.
Please review. I tested responsiveness on all device types.
Thank you.
=> Add new video to home page

guides/security.md
@phdunham Pointed out that the cookie name was incorrect in the Clickup ticket: https://app.clickup.com/t/4205457/XDN-15510
=> Fix cookie name for local http emulation

guides/cookbook.md
Text and example code used different domain names (example.com vs mydomain.com
=> Fix for typo

guides/next_commerce.md
I still haven't fixed my signed commits issue. Apologies
=> Correct instructions for Next Commerce 'Getting Started' section

guides/guides.json, pages/index.js
I tested locally on different screen sizes.
=> Add Vimeo videos to homepage

src/data/SidebarMenuItems.tsx
=> link to vimeo and remove prod updates

src/components/Layout/Sidebar/Sidebar.tsx
=> overflow-sidebar

src/pages/guides/traditional_sites.md
The old URL became inaccessible
=> Update Origin Content Changes Worksheet URL

src/pages/guides/split_testing.md
=> Fixed a typo on split_changes.md

src/pages/guides/routing.md
Complements https://github.com/layer0-docs/layer0-docs/pull/365/files 
Requires https://github.com/moovweb/xdn/pull/1311
=> APPOPS-12771: routing guide modification JWT

src/pages/guides/graphql.md
- https://app.clickup.com/t/4205457/APPOPS-14022
=> APPOPS-14022: Improve docs in regards of graphqlOperation and Apollo

src/pages/guides/response_headers.md
More context [in the Slack thread](https://llnw.slack.com/archives/C02T3QP4MV4/p1657641841538829)
=> Add pu status header component definition

src/pages/guides/response_headers.md
Documents the 'pu' component that can be present in response headers.
=> Document 'pu' component of response headers

src/pages/guides/umijs.md
=> Remove extra parenthesis in UmiJS Guide

.github/workflows/deploy-stage.yml, package.json
Reverts layer0-docs/layer0-docs#428
=> Revert "Test edgio-deploy action"

src/pages/guides/caching.md
- https://app.clickup.com/t/4205457/APPOPS-13055
=> APPOPS-13055: document hit-for-pass

src/pages/guides/response_headers.md
Document Kolben response header component.
=> Document "ek" response header component

src/pages/guides/core_web_vitals.md
This new section describes the caching behaviour of @edgio/rum and custom cache TTL option.
=> Added section about cache-manifest.js caching by @edgio/rum

src/pages/guides/astro.md
With https://github.com/edgio-docs/edgio-connectors/tree/main/edgio-astro-connector released, ask users to use connector with Edgio CLI.
=> Document @edgio/astro connector for Astro Apps

src/pages/guides/response_headers.md
Co-authored-by: Tom Karwowski <tkarwowski@llnw.com>
Documents new response fields for bot management. Should be merged after the release of Kolben 0.4.4
=> Document new response fields for bot management

.github/workflows/deploy-prod.yml, .github/workflows/deploy-stage.yml
The v1 are going to be deprecated soon.
=> Update actions versions

src/pages/guides/devtools.md
Dependent on https://github.com/storefront-foundation/react-storefront-starter-app/pull/112
=> Update RSF link in Devtools guide

src/pages/guides/devtools.md
Dependent on https://github.com/storefront-foundation/react-storefront-starter-app/pull/112
=> (4.x) Update RSF link in Devtools guide

src/pages/guides/logs.md
This change adds description for new access log fields.
=> Add new access log fields

src/pages/guides/sites_frameworks/getting_started.md
Updates "Edgio’s serverless workers" to "Edgio Serverless Compute"
=> Update Serverless Compute product name in intro

src/config/base.config.js, src/guides/performance/caching.md, src/guides/performance/cdn_as_code.md, src/guides/performance/cdn_as_code/common_routing_patterns.md, src/guides/performance/cdn_as_code/getting_started.md, src/guides/performance/unit_testing_edgejs.md, src/guides/v7/intro.md
Adds a warning for RouteHelper
=> V7 routehelper

scripts/prepBuild.js
**NOTICE FOR DEPLOY TARGETS**
`main` is the (default) target branch for deploying to https://docs.edg.io relating to `@edgio` v5.x.
`main_v4` is the target branch for deploying to https://docs.layer0.co relating to `@layer0` 4.x.
If your change request applies to both versions, please create a pull request for both target branches.
-- You may remove this message --
=> Fix removing of ssr pages

src/guides/security/tls_certificates.md
=> V7 tls cert changes

.github/workflows/deploy-prod.yml, .github/workflows/deploy-stage.yml, routes.ts, src/components/Docs/DocsFooter.tsx, src/guides/performance/cdn_as_code/getting_started.md, src/pages/guides/[...slug].tsx, src/pages/guides/[version]/changelog.tsx, src/pages/guides/changelog.tsx, src/utils/hooks/useConditioning.tsx
- Changelog is version-specific and generated at build-time with ISG
- Updated `useCondition` hook to determine the version from the route `slug` param (current behavior) or the `version` param (new, used by changelog)
- add in links to API docs
=> Versioned changelog

src/components/Layout/Header/VersionChooser.tsx, src/pages/guides/[...slug].tsx, src/utils/hooks/useConditioning.tsx
Reverts edgio-docs/edgio-docs#735
=> Revert "Always include version in path, including latest version"

src/guides/basics/deployments.md, src/guides/develop/cli.md, src/guides/performance/purging.md, src/guides/v5/develop/cli.md, src/guides/v6/develop/cli.md, src/guides/v7/upgrading.md
There will be definitely more places but this is something we just spotted.
=> EDGSITES-2 Update the guide to use --property

artifacts/deploy/edgio.yml
- Updating deploy conditions
- Adding release types
=> Update edgio.yml artifacts

artifacts/deploy/edgio.yml
Updating the edgio.yml file in artifacts to include the new requirements for the sites page. Changes include:
- Remove worker dispatch
- commit files against current PR branch
- lock file check(using '--frozen-lockfile' for now as this is backwards compatible. This will eventually be depreciated in the future)
- package manager check
- parse deploy links from deployment-manifest.json file
=> [EDGSITES-450] - Edgio Artifacts Update

src/guides/v7/basics/deployments.md
I've also reduced the code comments within the template since they are already described above.
=> [COMSUP-170] Update GitHub action template

rest_api/openapi/components/schemas/Limit.yaml, rest_api/openapi/components/schemas/LimitsAction.yaml, rest_api/openapi/components/schemas/Target.yaml, rest_api/openapi/components/schemas/TargetType.yaml
RL API descriptions now differentiate between Premier customers and lower levels
=> Updated descriptions for RL API

src/config/v7.nav.js, src/guides/v7/ai_integrations.md, src/guides/v7/ai_integrations/cohere.md, src/guides/v7/ai_integrations/langchain.md, src/guides/v7/ai_integrations/llamaindex.md, src/guides/v7/ai_integrations/mistral.md
See PR with [example code here](https://github.com/edgio-docs/edgio-examples/pull/121).
=> Add Cohere example

guides/applications/v7/performance/rules/conditions.md, guides/applications/v7/reference/country_codes.md, guides/applications/v7/security/custom_rules.md
Add instructions for region code
=> Update country_codes.md to include region code instructions

guides/applications/v7/security/asm.md
This adds suggested cleanup for ASM asset scanning description
only thing i changed is AWS GuardDuty -> Amazon GuardDuty
=> CON-2448 Additional ASM feedback integrated
