edgio-docs/edgio-docs

- guides/deploying.md
While I was following the GitHub Actions for deploying on Layer0, I placed the env variables referenced in the workflow to GitHub Secrets. After this didn't work, I reached out to support and it seems like just layer0_deploy_token needs to be added for deploying via CI, but other environment variables need to be added on Layer0 as per the [doc](https://docs.layer0.co/guides/environments#section_accessing_environment_variables_at_build_time).
Creating this pull request to link the sections as this would save lot of time scanning through docs to locate the answer and clear the confusion as to where shall the env. variables be placed during build time and for server computations (like as done in SSG/SSR)
> Clear the confusion of where to include the env variables

- guides/next.md
Guide was missing this piece and it is unclear that it is necessary without it (Files end up in s3 but not lambda)
> Update Next i18n guide to include includeFiles option in layer.config.js

- guides/connectors.md
- guides/cookbook.md
Connector docs / docs in general didn't have any obvious references to using BACKENDS.js (__js__) so ended up being kind of an unknown magic thing, I assume it's OK to add this
> Add example proxying to serverless to connectors guide

- pages/_app.js
The same link tag is used to load the font in [_document.js](https://github.com/layer0-docs/layer0-docs/blob/master/pages/_document.js#L33).
> Remove duplicate requests to load font

- guides/swell.md
By default swell is exported as a static app which doesn't require any dependencies to be included apart from the ones by default:
Working example: https://demos-swell-origin-theme-default.layer0-limelight.link/
Generating pages on demand example requires dependencies in the `modules` folder, so that shall be included manually.
https://demos-swell-origin-theme-default.layer0-limelight.link/products/pordtc-8
Can be easily verified from the source code of both the pages, for the latter it says which is accessed at the runtime:
```
!!! AUTOGENERATED FILE !!!
```
> Include ISG with Swell

- guides/webapp_cdn_getting_started.md
1. Removed what's after deploy your site: "..." because that is repetitive to the introduction line,
2. Even if the user goes ahead with the UI, right after the first click, they've to deploy with the CLI anyways,
3. Added yarn command for installing Layer0 CLI,
4. The section `configure caching and prefetching` contained no instructions specific to prefetching, hence removed prefetching from the header,
5. Removed the sign up to deploy in the last section as that has been already covered in the 2nd header on the page itself
> Simplify getting started guide

- guides/angular.md
The current directions for Angular specify that you should run `ng add @nguniversal/express-engine` but running that command by itself returns an error:
```
$ ng add @nguniversal/express-engine
Skipping installation: Package already installed
Schematic input does not validate against the Schema: {}
Errors:
Data path "" should have required property 'clientProject'.
```
After some googling I found [this comment](https://github.com/angular/universal/issues/1118#issuecomment-457054924) that includes the `--clientProject` flag and indicates it is necessary.
> update angular directions

- guides/layer0_migration.md
- guides/production.md
- We went a bit too fast removing the CNAME option in the console. We're adding it back as an alternative to A records.
- Also changing IPs and CNAME for LLNW's ones instead of Fastly. Those should now be used by default for v4.
Let's wait for this change to go live before publishing this https://github.com/moovweb/le-deployer/pull/1331
> DNS setup: Add CNAME back and use LLNW ips instead of Fastly

- guides/guides.json
- guides/regions.md
Fixes are:
- In guides.json, change `"text": "Edge Network"` to  `"text": "Regions"`
- In regions.md, add new "Available Regions" section and list of regions. Be sure to check the XDN terminology in the new section.
> fix regions issues identified by Mark Brocato

- guides/caching.md
I fixed the link so it points to the `Preventing a Response from being Cached` section. That has the content originally pointed to by the link when the `disabled` section was added.
> fix link in 'disabled' section

- guides/performance.md
fix confusing typo in “Turn off caching when not needed” section
> fix confusing typo

- src/pages/guides/caching.md
Addressing the different documentations of excludeAllQueryParametersExcept in [Layer0 Docs](https://docs.layer0.co/guides/caching#customizing-the-cache-key) vs [Layer0 API Docs](https://docs.layer0.co/docs/api/core/classes/_router_customcachekey_.customcachekey.html#excludeallqueryparametersexcept).
[Thread on the confusion here.](https://llnw.slack.com/archives/C02TM9AC67Q/p1651821215896839?thread_ts=1651796145.478259&cid=C02TM9AC67Q)
> Clear confusion between excludeAllQueryParametersExcept and excludeQueryParameters

- src/pages/guides/angular.md
- src/pages/guides/devtools.md
- src/pages/guides/ember_fastboot.md
- src/pages/guides/frontity.md
- src/pages/guides/next_commerce.md
- src/pages/guides/nuxt.md
- src/pages/guides/nx.md
- src/pages/guides/production.md
- src/pages/guides/razzle.md
- src/pages/guides/react.md
- src/pages/guides/sapper.md
- src/pages/guides/spartacus.md
- src/pages/guides/static_sites.md
- src/pages/guides/vsf.md
- src/pages/guides/vsf1.md
Live links that point to `layer0.link` are no longer working. This fixes the links for a lot of our framework guides.
> Update Layer0 link domain name

- src/pages/guides/next.md
The one click URL had some bad HTML encoding in it.
> update url in next.md

- src/pages/guides/react.md
When using the copy-and-paste method, the `Prefetcher` class is undefined.
> clarify prefetcher example

- src/pages/guides/ember_fastboot.md
The current version uses `import { install } from '0/prefetch/window';` and ` connector: '0/fastboot',` which are incorrect. The docs were using `{{ CLI_NAME }}` for both of these when `{{ PACKAGE_NAME }}` should have been used instead. 
```
'0/prefetch/window' -> '@layer0/prefetch/window'
'0/fastboot' -> '@layer0/fastboot'
```
> Fix referenced constants in Fastboot Guide

- src/pages/guides/logs.md
**NOTICE FOR DEPLOY TARGETS**
`main` is the (default) target branch for deploying to https://docs.edg.io relating to `@edgio` v5.x.
`main_v4` is the target branch for deploying to https://docs.layer0.co relating to `@layer0` 4.x.
If your change request applies to both versions, please create a pull request for both target branches.
-- You may remove this message --
> Added definitions for ac and ce access log fields

- src/pages/guides/sites_frameworks/getting_started/hexo.md
**NOTICE FOR DEPLOY TARGETS**
`main` is the (default) target branch for deploying to https://docs.edg.io relating to `@edgio` v5.x.
`main_v4` is the target branch for deploying to https://docs.layer0.co relating to `@layer0` 4.x.
If your change request applies to both versions, please create a pull request for both target branches.
-- You may remove this message --
> Document @edgio/hexo connector

- src/pages/guides/performance/observability/core_web_vitals.md
https://app.clickup.com/t/4205457/APPOPS-17392
https://github.com/layer0-platform/rum/pull/37
We track CWV on all browsers which support server timings , IE and Safari don't support that.
> APPOPS-17392 Add info about tracked browsers

- constants.js
- src/pages/guides/performance/observability/devtools.md
Because of https://docs.edg.io/guides/performance/observability/devtools#per-environment
> Fix PRODUCT_UPPER

- src/guides/v7/sites_frameworks/getting_started/next.md
We changed how devtools are injected, so this PR should cover this.
Also, note added for Next 13, as by default injecting SW on root components (app folder) will fail the build.
> Added description for devtools and note for SW

- package.json
- src/components/Layout/Header/Header.tsx
- src/components/Layout/Page.tsx
- yarn.lock
Reduces conflict of some encoded characters in the hash.
Before: `https://docs.edg.io/guides/v7/logs/server_logs#RGVlcCBSZXF1ZXN0IEluc3BlY3Rpb24gKERSSSk=`
After:    `https://docs.edg.io/guides/v7/logs/server_logs#~(q~'Deep*20Request*20Inspection*20*28DRI*29)`
Also follows similar pattern to Chrome's *Copy Link to Highlight*: `https://docs.edg.io/guides/v7/logs/server_logs#:~:text=Deep%20Request%20Inspection%20(DRI)%20%23`
> [COMSUP-153] Use JSURL to serialize search result instead of encodedURIComponent

- src/guides/v7/performance/cdn_as_code/route_features.md
The original documentation using `set_origin` was incorrect. `renderWithApp()` also sets a hint request header for the internal function index that needs to be executed in the cloud.
> [COMSUP-172] Route to cloud functions using renderWithApp()

- src/guides/v7/performance/cdn_as_code/edgio_config.md
I've also pulled in the latest (7.3) config file contents, which doesn't reflect current terminology (serverless vs cloud).
> [COMSUP-171] Add `scheme` to config; update latest config file

- src/guides/v7/edge_functions/examples/aws_request_signing.md
Reverted back to `whatwg-url` due to missing `searchParams` support of `url-parse`. This will be updated later in COMSUP-254 with the EF utilities package.
> AWS Request Signing Dependencies 

- src/guides/v7/basics/origins.md
- src/guides/v7/performance/troubleshooting.md
- src/guides/v7/security/tls_certificates.md
adds another common use case encountered during setup
> 504 status code, add troubleshooting cross-reference to TLS 

- guides/applications/v4/production.md
- guides/applications/v4/teams.md
Discovered by crawl, resulted in `/[product]/environments` as the path.
> Invalid links in v4 guides

- guides/applications/v7/edge_functions.md
Documentation for Request URL changes to the Edge Function `Request` class in v7.13.6
> Document Edge Function Request.url changes
